# 1. IDENTITY AND ACCESS MANAGEMENT
output "aws_mfa_is_not_enabled_on_root_account_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_aws_mfa_is_not_enabled_on_root_account.csrs_id
}
output "aws_access_key_enabled_on_root_account_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_aws_access_key_enabled_on_root_account.csrs_id
}
output "aws_access_keys_are_not_rotated_for_90_days_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_aws_access_keys_are_not_rotated_for_90_days.csrs_id
}
output "azure_sql_server_not_configured_with_active_directory_admin_authentication_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_azure_sql_server_not_configured_with_active_directory_admin_authentication.csrs_id
}
output "aws_mfa_not_enabled_for_iam_users_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_aws_mfa_not_enabled_for_iam_users.csrs_id
}
output "aws_iam_password_policy_is_unsecure_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_aws_iam_password_policy_is_unsecure.csrs_id
}
output "aws_iam_password_policy_does_not_have_password_expiration_period_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_aws_iam_password_policy_does_not_have_password_expiration_period.csrs_id
}
# 2. STORAGE
output "azure_microsoft_defender_for_cloud_is_set_to_off_for_azure_sql_databases_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_azure_microsoft_defender_for_cloud_is_set_to_off_for_azure_sql_databases.csrs_id
}
output "aws_rds_snapshots_are_accessible_to_public_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_aws_rds_snapshots_are_accessible_to_public.csrs_id
}
output "azure_storage_account_using_insecure_tls_version_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_azure_storage_account_using_insecure_tls_version.csrs_id
}
output "azure_mysql_database_flexible_server_using_insecure_tls_version_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_azure_mysql_database_flexible_server_using_insecure_tls_version.csrs_id
}
output "aws_rds_database_instance_is_publicly_accessible_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_aws_rds_database_instance_is_publicly_accessible.csrs_id
}
output "azure_mysql_database_server_ssl_connection_is_disabled_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_azure_mysql_database_server_ssl_connection_is_disabled.csrs_id
}
output "aws_s3_buckets_are_accessible_to_public_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_aws_s3_buckets_are_accessible_to_public.csrs_id
}
output "aws_ebs_snapshots_are_accessible_to_public_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_aws_ebs_snapshots_are_accessible_to_public.csrs_id
}
output "azure_storage_account_container_storing_activity_logs_is_publicly_accessible_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_azure_storage_account_container_storing_activity_logs_is_publicly_accessible.csrs_id
}
output "azure_storage_account_has_a_blob_container_with_public_access_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_azure_storage_account_has_a_blob_container_with_public_access.csrs_id
}
output "aws_s3_buckets_are_accessible_to_any_authenticated_user_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_aws_s3_buckets_are_accessible_to_any_authenticated_user.csrs_id
}
output "azure_microsoft_defender_for_cloud_is_set_to_off_for_sql_servers_on_machines_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_azure_microsoft_defender_for_cloud_is_set_to_off_for_sql_servers_on_machines.csrs_id
}
# 3. COMPUTE
output "azure_acr_https_not_enabled_for_webhook_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_azure_acr_https_not_enabled_for_webhook.csrs_id
}
output "azure_microsoft_defender_for_cloud_is_set_to_off_for_app_service_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_azure_microsoft_defender_for_cloud_is_set_to_off_for_app_service.csrs_id
}
output "aws_ec2_instance_not_configured_with_instance_metadata_service_v2_imdsv2_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_aws_ec2_instance_not_configured_with_instance_metadata_service_v2_imdsv2.csrs_id
}
output "aws_amazon_machine_image_ami_is_publicly_accessible_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_aws_amazon_machine_image_ami_is_publicly_accessible.csrs_id
}
output "azure_application_gateway_does_not_have_the_web_application_firewall_waf_enabled_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_azure_application_gateway_does_not_have_the_web_application_firewall_waf_enabled.csrs_id
}
output "azure_app_service_web_app_doesnt_use_latest_tls_version_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_azure_app_service_web_app_doesnt_use_latest_tls_version.csrs_id
}
output "aws_eks_cluster_endpoint_access_publicly_enabled_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_aws_eks_cluster_endpoint_access_publicly_enabled.csrs_id
}
# 4. NETWORKING
output "aws_web_application_firewall_aws_waf_classic_logging_is_disabled_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_aws_web_application_firewall_aws_waf_classic_logging_is_disabled.csrs_id
}
output "azure_network_security_group_allows_all_traffic_on_sql_server_udp_port_1434_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_azure_network_security_group_allows_all_traffic_on_sql_server_udp_port_1434.csrs_id
}
output "azure_network_security_group_allows_all_traffic_on_netbios_dns_tcp_port_53_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_azure_network_security_group_allows_all_traffic_on_netbios_dns_tcp_port_53.csrs_id
}
output "azure_network_security_group_allows_all_traffic_on_rdp_port_3389_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_azure_network_security_group_allows_all_traffic_on_rdp_port_3389.csrs_id
}
output "aws_security_group_allows_all_ipv6_traffic_on_rdp_port_3389_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_aws_security_group_allows_all_ipv6_traffic_on_rdp_port_3389.csrs_id
}
output "aws_api_gateway_with_public_endpoints_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_aws_api_gateway_with_public_endpoints.csrs_id
}
output "azure_network_security_group_allows_all_traffic_on_postgresql_tcp_port_5432_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_azure_network_security_group_allows_all_traffic_on_postgresql_tcp_port_5432.csrs_id
}
output "azure_network_security_group_allows_all_traffic_on_mysql_tcp_port_3306_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_azure_network_security_group_allows_all_traffic_on_mysql_tcp_port_3306.csrs_id
}
output "azure_network_security_group_allows_all_traffic_on_netbios_udp_port_137_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_azure_network_security_group_allows_all_traffic_on_netbios_udp_port_137.csrs_id
}
output "azure_network_security_group_allows_all_traffic_on_icmp_ping_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_azure_network_security_group_allows_all_traffic_on_icmp_ping.csrs_id
}
output "azure_network_security_group_allows_all_traffic_on_ftp-data_tcp_port_20_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_azure_network_security_group_allows_all_traffic_on_ftp-data_tcp_port_20.csrs_id
}
output "aws_cloudfront_web_distribution_using_insecure_tls_version_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_aws_cloudfront_web_distribution_using_insecure_tls_version.csrs_id
}
output "azure_network_security_group_allows_all_traffic_on_netbios_dns_udp_port_53_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_azure_network_security_group_allows_all_traffic_on_netbios_dns_udp_port_53.csrs_id
}
output "azure_network_security_group_allows_all_traffic_on_vnc_server_tcp_port_5900_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_azure_network_security_group_allows_all_traffic_on_vnc_server_tcp_port_5900.csrs_id
}
output "azure_network_security_group_allows_all_traffic_on_telnet_tcp_port_23_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_azure_network_security_group_allows_all_traffic_on_telnet_tcp_port_23.csrs_id
}
output "azure_network_security_group_allows_all_traffic_on_smtp_tcp_port_25_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_azure_network_security_group_allows_all_traffic_on_smtp_tcp_port_25.csrs_id
}
output "aws_security_group_allows_all_ipv6_traffic_on_ssh_port_22_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_aws_security_group_allows_all_ipv6_traffic_on_ssh_port_22.csrs_id
}
output "aws_elastic_load_balancer_classic_ssl_negotiation_policy_configured_with_vulnerable_ssl_protocol_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_aws_elastic_load_balancer_classic_ssl_negotiation_policy_configured_with_vulnerable_ssl_protocol.csrs_id
}
output "azure_network_security_group_allows_all_traffic_on_vnc_listener_tcp_port_5500_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_azure_network_security_group_allows_all_traffic_on_vnc_listener_tcp_port_5500.csrs_id
}
output "azure_network_security_group_allows_all_traffic_on_windows_smb_tcp_port_445_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_azure_network_security_group_allows_all_traffic_on_windows_smb_tcp_port_445.csrs_id
}
output "azure_network_security_group_allows_all_traffic_on_cifs_udp_port_445_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_azure_network_security_group_allows_all_traffic_on_cifs_udp_port_445.csrs_id
}
output "azure_network_security_group_allows_all_traffic_on_ssh_port_22_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_azure_network_security_group_allows_all_traffic_on_ssh_port_22.csrs_id
}
output "aws_security_group_allows_all_ipv4_traffic_on_ssh_port_22_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_aws_security_group_allows_all_ipv4_traffic_on_ssh_port_22.csrs_id
}
output "azure_network_security_group_allows_all_traffic_on_msql_tcp_port_4333_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_azure_network_security_group_allows_all_traffic_on_msql_tcp_port_4333.csrs_id
}
output "azure_network_security_group_allows_all_traffic_on_windows_rpc_tcp_port_135_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_azure_network_security_group_allows_all_traffic_on_windows_rpc_tcp_port_135.csrs_id
}
output "azure_network_security_group_having_inbound_rule_overly_permissive_to_all_traffic_on_any_protocol_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_azure_network_security_group_having_inbound_rule_overly_permissive_to_all_traffic_on_any_protocol.csrs_id
}
output "aws_elastic_load_balancer_classic_ssl_negotiation_policy_configured_with_insecure_ciphers_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_aws_elastic_load_balancer_classic_ssl_negotiation_policy_configured_with_insecure_ciphers.csrs_id
}
output "aws_security_group_allows_all_ipv4_traffic_on_rdp_port_3389_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_aws_security_group_allows_all_ipv4_traffic_on_rdp_port_3389.csrs_id
}
output "azure_network_security_group_allows_all_traffic_on_ftp_tcp_port_21_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_azure_network_security_group_allows_all_traffic_on_ftp_tcp_port_21.csrs_id
}
output "azure_network_security_group_allows_all_traffic_on_netbios_udp_port_138_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_azure_network_security_group_allows_all_traffic_on_netbios_udp_port_138.csrs_id
}
output "azure_network_security_group_having_inbound_rule_overly_permissive_to_all_traffic_on_udp_protocol_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_azure_network_security_group_having_inbound_rule_overly_permissive_to_all_traffic_on_udp_protocol.csrs_id
}
output "azure_network_security_group_having_inbound_rule_overly_permissive_to_all_traffic_on_tcp_protocol_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_azure_network_security_group_having_inbound_rule_overly_permissive_to_all_traffic_on_tcp_protocol.csrs_id
}
output "azure_virtual_network_subnet_is_not_configured_with_a_network_security_group_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_azure_virtual_network_subnet_is_not_configured_with_a_network_security_group.csrs_id
}
output "azure_network_security_group_allows_all_traffic_on_sql_server_tcp_port_1433_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_azure_network_security_group_allows_all_traffic_on_sql_server_tcp_port_1433.csrs_id
}
output "aws_elastic_load_balancer_elb_with_acm_certificate_expired_or_expiring_in_90_days_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_aws_elastic_load_balancer_elb_with_acm_certificate_expired_or_expiring_in_90_days.csrs_id
}
# 5. DATA SERVICES
# 6. LOGGING AND MONITORING
output "aws_vpc_flow_logs_not_enabled_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_aws_vpc_flow_logs_not_enabled.csrs_id
}
output "aws_cloudtrail_is_not_enabled_on_the_account_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_aws_cloudtrail_is_not_enabled_on_the_account.csrs_id
}
output "aws_cloudtrail_logging_is_disabled_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_aws_cloudtrail_logging_is_disabled.csrs_id
}
output "azure_key_vault_audit_logging_is_disabled_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_azure_key_vault_audit_logging_is_disabled.csrs_id
}
# 7. MESSAGING
# 8. SUPPORTING SERVICES
output "aws_secrets_manager_secret_rotation_is_not_enabled_csrs_id" {
  value = prismacloud_compliance_standard_requirement_section.csrs_aws_secrets_manager_secret_rotation_is_not_enabled.csrs_id
}
# 9. OTHER SECURITY CONSIDERATIONS
